### ISSUE TITLE
You have an Application Programming Interface key in your code

### ISSUE THREAD

**Issue by fhightower** [james-fray/download-virus-check#1]
You should remove your key from the code here: https://github.com/james-fray/download-virus-check/blob/master/common.js#L15.

**Comment by james-fray** [comment]
Do you have any idea how to hide a key in a Chrome extension? The best that I know is to use a simple encoding like base64 encoding for instance.

**Comment by fhightower** [comment]
Ah, sorry about that. I didn't realize this used in a chrome extension. In that case, I don't know of any way to truly hide it and this is fine if you are already sharing your API key as part of the extension.
